name: PR lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: seferov/pr-lint-action@master
      with:
        title-regex: '(^(workflow|backend|frontend|build|ci|docs|fix|perf|refactor|style|test|intergration|release|merge):(.{1,}(?=\w*))|^(Bump.*\/services))'